notifications:
  email:
    - bart@mynameisbart.com

language: php

php:
  - 5.5
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  # Download Drupal core.
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --branch 8.0.x --depth 1 http://git.drupal.org/project/drupal.git

  # Copy Payment into Drupal core.
  - cp -Rv $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/modules/payment

  # Download module dependencies.
  - cd $TRAVIS_BUILD_DIR/../drupal/modules
  - git clone --branch 8.x-3.x --depth 1 http://git.drupal.org/project/currency.git
  - git clone --branch 8.x-2.x --depth 1 http://git.drupal.org/project/plugin.git

  # Install Composer dependencies.
  - cd $TRAVIS_BUILD_DIR/../drupal/modules/payment
  - composer install

script:
  # Run PHPUnit tests and submit code coverage statistics.
  - cd $TRAVIS_BUILD_DIR/../drupal/modules/payment
  - mkdir -p build/logs
  - ../../core/vendor/bin/phpunit -c ./phpunit.xml.dist --bootstrap ../../core/tests/bootstrap.php --verbose --debug --coverage-clover ./build/logs/clover.xml || exit 1
  - php ./vendor/bin/coveralls -v -c ./.coveralls.yml
