payment_form.payment_type:
  label: Payment Form configuration
  mapping:
    allowed_plugin_ids:
      label: Allowed payment method plugin IDs
      sequence:
        - label: Payment method plugin ID
          type: string
      type: sequence
    limit_allowed_plugins:
      label: Limit allowed payment methods
      type: boolean
    plugin_selector_id:
      label: Plugin selector ID
      type: string
    plugin_selector_configuration:
      label: Plugin selector configuration
      type: plugin.plugin_configuration.selector.[%parent.plugin_selector_id]
  type: mapping

payment.plugin_configuration.payment_type.payment_form:
  label: Payment Form payment type configuration
  mapping:
    bundle:
      label: Bundle
      type: string
    destination_url:
      label: Destination URL
      type: uri
    entity_type_id:
      label: Entity type ID
      type: string
    field_name:
      label: Field name
      type: string
  type: mapping

field.field_settings.payment_form:
  type: mapping
  label: Payment form field settings
  mapping:
    currency_code:
      type: string
      label: The currency code

field.value.payment_form:
  label: Payment form field value
  mapping:
    plugin_id:
      label: Plugin ID
      type: string
    plugin_configuration:
      label: Plugin configuration
      type: payment.plugin_configuration.line_item.[%parent.plugin_id]
  type: mapping
